export const PRODUCT_LIST_REQ='PRODUCT_LIST_REQ';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQ='PRODUCT_DETAILS_REQ';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

export const CARD_ADD_ITEM ='CARD_ADD_ITEM';

export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";

export const USER_SIGN_REQUEST= 'USER_SIGN_REQUEST';
export const USER_SIGN_SUCCESS= 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL= 'USER_SIGN_FAIL';

export const USER_REGISTER_REQUEST= 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS= 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL= 'USER_REGISTER_FAIL';

export const CART_SAVE_SHIPPIN = 'CART_SAVE_SHIPPIN';
export const CART_SAVE_PAYMENT='CART_SAVE_PAYMENT'

export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS='ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL='ORDER_CREATE_FAIL';
